# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 115f40a7bcfd51d9a15bc3b28b0e2cbe591b507cda292d71a32a4345775897825cf81f8b9836175fb20d354ebdd21c12985d3c79c8b1fb78ed280cb01fd94164

test:
  secret_key_base: 5ad950f4ce41ce1aa3adc2be80b131d5490a111e7f3a6c1287aef77380e616f2c2d1a85cbda1e3249e5be3e76ec41dd44f8a71deeda574c43a4ff3e32fbd736f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
